apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: p-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: p-tekton-triggers-admin
    rules:
      - apiGroups:
          - triggers.tekton.dev
        resources:
          - eventlisteners
          - triggerbindings
          - triggertemplates
        verbs:
          - get
      - apiGroups:
          - tekton.dev
        resources:
          - pipelineruns
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: p-clone-push
    secrets:
      - name: p-image-registry
  - apiVersion: v1
    data:
      .dockerconfigjson: PFRPRE86IGluc2VydCB5b3VyIGRvY2tlciBjb25maWcganNvbj4=
    kind: Secret
    metadata:
      annotations:
        tekton.dev/docker-0: ""
      creationTimestamp: null
      name: p-image-registry
    type: kubernetes.io/dockerconfigjson
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: p
      name: p
    spec:
      rules:
        - host: p.com
          http:
            paths:
              - backend:
                  service:
                    name: el-p-git-repo
                    port:
                      name: port-8080
                path: /el-p-git-repo
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: TriggerTemplate
    metadata:
      creationTimestamp: null
      name: p-run-clone-build-push
    spec:
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            creationTimestamp: null
            name: p-clone-build-push-$(uid)
          spec:
            params:
              - name: image-registry-url
                value: quay.io/p
            pipelineRef:
              name: p-clone-build-push
            serviceAccountName: p-clone-push
            workspaces:
              - name: p-shared-data
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    storageClassName: default
                  status: {}
          status: {}
    status: {}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: p-tekton-triggers-admin
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      creationTimestamp: null
      name: p-clone-build-push
    spec:
      params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
      tasks:
        - name: clone-1
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: p-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/git-prompt
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/output/dot_oh-my-zsh/plugins/git-prompt/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/output/dot_oh-my-zsh/plugins/git-prompt'
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: p-shared-data
            - name: dockerconfig
              workspace: registry-credentials
      workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: p-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-ssh-credentials
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: TriggerBinding
    metadata:
      creationTimestamp: null
      name: p-git-event
    spec: {}
    status: {}
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: EventListener
    metadata:
      creationTimestamp: null
      name: p-git-repo
    spec:
      namespaceSelector: {}
      resources: {}
      serviceAccountName: p-tekton-triggers-admin
      triggers:
        - bindings:
            - ref: p-git-event
          template:
            ref: p-run-clone-build-push
    status:
      configuration:
        generatedName: ""
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: null
      name: p-tekton-triggers-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: p-tekton-triggers-admin
    subjects:
      - kind: ServiceAccount
        name: p-tekton-triggers-admin
parameters: []
